### ISSUE TITLE
Question on scene scaling

### ISSUE THREAD

**Issue by Gaaaavin** [graphdeco-inria/hierarchical-3d-gaussians#46]
I noticed that in [auto_reorient.py](https://github.com/graphdeco-inria/hierarchical-3d-gaussians/blob/3c601568d3c0557cee3840e4ef79dce3a60ec02b/preprocess/auto_reorient.py#L83), the scene is scaled so that the average point to camera-center distance is 20m.
I'm curious what's the reason for this number. Is that purly based on experience?

**Comment by ameuleman** [comment]
Hi, 
Our datasets are scaled to metric using some measurements, such as car or road lengths. 
For our code release, we then estimated the median point-to-camera distance for one of our datasets (SmallCity) and found it to be roughly 20. We used it in the auto_reorient script to maintain a similar behaviour.

**Comment by Gaaaavin** [comment]
Thank you for the clarification!

**Comment by HaedamOh** [comment]
Hi, I play with scale parameter since I also try to convert COLMAP to metric scale on real-world dataset 

I have noticed some weird behaviour when I set scale too high, e.g) scale =~ 10 or camera-to-center distance =~ 100m 

The quality significantly downgraded and floating effects occurred. 

I could observed that far object ( e.g buildings ) is not reconstructed properly and appear close to camera plane as floaters.

But, If I stick with small scale ( direct output of COLMAP) , reconstruction works fine.

Is there a particular reason for this? is renderer limits far-away object reconstruction? 

Thank you
